version: '3.7'

services:
  backend:
    image: backend-img
    build:
      context: .
      dockerfile: backend.dockerfile
    restart: always
    env_file:
      - ./.env
    ports:
      - "8091:80"
    volumes:
      - .:/app/
    depends_on:
      - redis
      - db

  db:
    image: postgres:14
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data/pgdata
    env_file:
      - ./.env
    ports:
      - 5433:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  redis:
    image: redis:7.0.6
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
